### ISSUE TITLE
Fix load hospital data migration with Pandas

### ISSUE THREAD

**Issue by arich** [arich/hospital_readmission_server#1]
Run `mix ecto.migrate`, and the current migration (CopyHospitalCSV) fails. This is because we're trying to insert text "Not Available" into an integer column. Instead we need to null these fields. This is probably best done with Pandas, from what I've read it can process a csv file into a sql file for inserting. 

It's possible we could also do this by find replacing all "Not Available"s with NULLs, but Pandas seems like it's made for this task (data cleaning). Generate a clean sql file for adding the hospital data to the hospitals table, and modify the migration to run that file instead. 

Error below:

```
22:20:54.421 [info]  execute "  COPY hospitals(\n    name,\n    provider_number,\n    state,\n    measure_name,\n    number_of_discharges,\n    footnote,\n    excess_readmission_ratio,\n    predicted_readmission_ratio,\n    expected_readmission_rate,\n    number_of_readmissions,\n    start_date,\n    end_date\n  )\n  FROM '/home/andrew/projects/hospital_readmission_server/priv/repo/data_files/Hospital_Readmissions_Reduction_Program.csv'\n  WITH CSV HEADER;\n"
** (Postgrex.Error) ERROR (invalid_text_representation): invalid input syntax for integer: "Not Available"
```

**Comment by ezbc** [comment]
I replaced any instances of 'Not Available' with numpy.nan. This should be interpretable by SQL (I hope).

Next time I'll do a pull request.

**Comment by arich** [comment]
YOU BETTER

**Comment by ezbc** [comment]
😁

**Comment by arich** [comment]
Did you push your changes to origin?

**Comment by ezbc** [comment]
I did.
https://github.com/ezbc/Hospital_Readmission/blob/master/scripts/reformat_data.py#L82

Did you rerun the `reformat_data.py` script?

On Sun, Feb 28, 2016 at 11:19 AM, Andrew Rich notifications@github.com
wrote:

> Did you push your changes to origin?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arich/hospital_readmission_server/issues/1#issuecomment-189910685
> .

## 

Elijah Bernstein-Cooper
ezbc@astro.wisc.edu
Department of Astronomy
University of Wisconsin - Madison

**Comment by ezbc** [comment]
And I'm a fool. I forgot to assign the output of replacing 'Not Available'
to the DataFrame.

See the pull request https://github.com/ezbc/Hospital_Readmission/pull/2
in the scripts repo.

On Sun, Feb 28, 2016 at 1:29 PM, Elijah Bernstein-Cooper <
ezbc@astro.wisc.edu> wrote:

> I did.
> 
> https://github.com/ezbc/Hospital_Readmission/blob/master/scripts/reformat_data.py#L82
> 
> Did you rerun the `reformat_data.py` script?
> 
> On Sun, Feb 28, 2016 at 11:19 AM, Andrew Rich notifications@github.com
> wrote:
> 
> > Did you push your changes to origin?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arich/hospital_readmission_server/issues/1#issuecomment-189910685
> > .
> 
> ## 
> 
> Elijah Bernstein-Cooper
> ezbc@astro.wisc.edu
> Department of Astronomy
> University of Wisconsin - Madison

## 

Elijah Bernstein-Cooper
ezbc@astro.wisc.edu
Department of Astronomy
University of Wisconsin - Madison

**Comment by arich** [comment]
So, we've got two separate repos going on right now. https://github.com/ezbc/Hospital_Readmission and  https://github.com/arich/hospital_readmission_server/. 

Which do you want to use?

**Comment by ezbc** [comment]
It's probably easier to migrate the data and the Python scripts to
hospital_readmission_server.

So lets keep hospital_readmission_server.

On Thu, Mar 3, 2016 at 4:02 PM, Andrew Rich notifications@github.com
wrote:

> So, we've got two separate repos going on right now.
> https://github.com/ezbc/Hospital_Readmission and
> https://github.com/arich/hospital_readmission_server/.
> 
> Which do you want to use?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arich/hospital_readmission_server/issues/1#issuecomment-191961394
> .

## 

Elijah Bernstein-Cooper
ezbc@astro.wisc.edu
Department of Astronomy
University of Wisconsin - Madison

**Comment by ezbc** [comment]
See pull request #4.
